name: Build Docker Image Nexus

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Nexus
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.NEXUS_REGISTRY }}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.NEXUS_REGISTRY }}/docker-hosted/stock-app:latest
            ${{ secrets.NEXUS_REGISTRY }}/docker-hosted/stock-app:${{ github.sha }}
